---
- name: install git
  apt: pkg=git-core state=installed

- name: get Dockerfile
  git: repo=https://github.com/p2pu/docker-images.git dest=/var/docker-images

- name: build docker image
  docker_image: path="/var/docker-images/knight-container" name="p2pu/knight-app" state=build

- name: create postgres user
  postgresql_user:
    name: "{{DB_USER}}"
    password: "{{DB_PASSWORD}}"
    login_host: "127.0.0.1"
    login_user: "{{PG_ADMIN_USER}}"
    login_password: "{{PG_ADMIN_PASSWORD}}"


- name: create postgres db
  postgresql_db:
    name: "{{DB_NAME}}"
    encoding: UTF-8
    login_host: "127.0.0.1"
    login_user: "{{PG_ADMIN_USER}}"
    login_password: "{{PG_ADMIN_PASSWORD}}"
    owner: "{{DB_USER}}"

- name: Knight app
  docker:
    name: p2pu-knight
    image: p2pu/knight-app:latest
    state: reloaded
    volumes:
    - "/var/p2pu/volumes/knight/static:/var/app/static_serve"
    links:
    - "p2pu-postgres:postgres"
    env:
      VIRTUAL_HOST: "chicago.p2pu.org"
      DATABASE_URL: "postgres://{{ DB_USER }}:{{ DB_PASSWORD }}@postgres:5432/{{DB_NAME}}"
      ADMIN_EMAIL: "{{ADMIN_EMAIL}}"
      SECRET_KEY: "{{SECRET_KEY}}"
      EMAIL_HOST: "{{EMAIL_HOST}}"
      ADMIN_EMAIL: "{{ADMIN_EMAIL}}"
      SECRET_KEY: "{{SECRET_KEY}}"
      ADMIN_EMAIL: "{{ADMIN_EMAIL}}"
      SECRET_KEY: "{{SECRET_KEY}}"
      EMAIL_HOST_USER: "{{EMAIL_HOST_USER}}"
      EMAIL_HOST_PASSWORD: "{{EMAIL_HOST_PASSWORD}}"
      DEFAULT_FROM_EMAIL: "{{DEFAULT_FROM_EMAIL}}"
      AWS_ACCESS_KEY_ID: "{{AWS_ACCESS_KEY_ID}}"
      AWS_SECRET_ACCESS_KEY: "{{AWS_SECRET_ACCESS_KEY}}"
      AWS_STORAGE_BUCKET_NAME: "{{AWS_STORAGE_BUCKET_NAME}}"
      TWILIO_ACCOUNT_SID: "{{TWILIO_ACCOUNT_SID}}"
      TWILIO_AUTH_TOKEN: "{{TWILIO_AUTH_TOKEN}}"
      TWILIO_NUMBER: "{{TWILIO_NUMBER}}"
